name: Terraform CI/CD

on:
  push:
    branches:
  
      - main   # מפעיל את ה־workflow רק כשיש push ל־main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # שלב 1 – משיכת הקוד מהריפו
      - name: Checkout repository
        uses: actions/checkout@v3

      # שלב 2 – התקנת Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # שלב 3 – קונפיגורציה של AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # שלב 4 – Terraform init
      - name: Terraform Init
        run: terraform init

      # שלב 5 – Terraform validate
      - name: Terraform Validate
        run: terraform validate

      # שלב 6 – Terraform plan
      - name: Terraform Plan
        run: terraform plan

      # שלב 7 – Terraform apply (רק אם את רוצה אוטומציה מלאה)
      - name: Terraform Apply
        run: terraform apply -auto-approve
